version: '3'
services:

  minio:
    image: bitnami/minio:latest
    hostname: minio
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./minio:/minio
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - bridge

  api:
    build: .
    depends_on:
      minio:
        condition: service_healthy
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8009:8000"
    networks:
      - bridge

networks:
  bridge:
   driver: bridge